In [ ]:
import numpy as np

arr1 = np.empty((2,2))
print(arr1)

[[2.83236177e-315 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [ ]:
arr1 = np.ones((4,2))
print(arr1)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
arr1 = np.full((4,2), 5)
print(arr1)

[[5 5]
 [5 5]
 [5 5]
 [5 5]]


In [ ]:
given = np.array([[1, 2, 3], [4, 5, 6]])
arr = np.zeros_like(given)

print(arr)

[[0 0 0]
 [0 0 0]]


In [ ]:
given = np.array([[1, 2, 3], [4, 5, 6]])
arr = np.ones_like(given)

print(arr)

[[1 1 1]
 [1 1 1]]


In [ ]:
new_list = [1,2,3,4]

arr = np.array(new_list)

print(arr, "- Type: ", type(arr))

[1 2 3 4] - Type:  <class 'numpy.ndarray'>


**Problem 2**

In [ ]:
np_range = np.arange(10, 49)

print(np_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
np_reshaped = np.arange(9).reshape((3,3))

print(np_reshaped)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
eyeMatrx = np.eye(3,3)
print(eyeMatrx)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
randomMatrx = np.random.random(30)

print(randomMatrx)
print("Mean of the above array", np.mean(randomMatrx))

[0.64816093 0.66263604 0.42229655 0.06888547 0.61502696 0.32395529
 0.62736166 0.15192105 0.56682504 0.40736384 0.78973941 0.05551206
 0.69372816 0.13216052 0.2700755  0.57763112 0.82840674 0.45354201
 0.60525054 0.27812277 0.60812624 0.39584322 0.03053247 0.74939473
 0.47604177 0.13182032 0.70603094 0.7998317  0.18162355 0.8925814 ]
Mean of the above array 0.47168093315906273


In [ ]:
randArray = np.random.random((10, 10))

maxValue = randArray.max()
minValue = randArray.min()

print("10x10 Random Array:\n", randArray)
print("\nMinimum value:", maxValue)
print("Maximum value:", minValue)

10x10 Random Array:
 [[0.08167722 0.77655493 0.00255423 0.40429203 0.47977747 0.42518604
  0.2316239  0.48851708 0.58083462 0.14925161]
 [0.72448302 0.56967641 0.17442227 0.35290973 0.46002591 0.8714907
  0.20384359 0.23582189 0.39223066 0.04189711]
 [0.18966713 0.71657374 0.8410947  0.44685887 0.15643005 0.53646081
  0.48541517 0.20116588 0.41440126 0.92696126]
 [0.23263472 0.82943444 0.01168399 0.57036045 0.7974078  0.95155436
  0.98380649 0.14053505 0.95810187 0.9941119 ]
 [0.3361045  0.76699847 0.43550251 0.12707385 0.26783548 0.84627954
  0.26365201 0.00474865 0.92545814 0.78707314]
 [0.46384714 0.09212094 0.54619567 0.0185637  0.58020023 0.17987011
  0.92768257 0.79079572 0.99651755 0.27944539]
 [0.99830424 0.9824559  0.57075894 0.1677076  0.11110555 0.53110608
  0.14172027 0.30384738 0.27948124 0.37013043]
 [0.08320394 0.83263019 0.22932468 0.9817107  0.08604267 0.96753005
  0.85528337 0.17463525 0.84561263 0.6707272 ]
 [0.03721435 0.03687521 0.13399286 0.2179942  0.13300187 0.8

In [ ]:
zeroArr = np.zeros(10)
print(zeroArr)

zeroArr[4] = 1
print(zeroArr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
arr1 = np.array([1,2,0,0,4,0])
reversed = arr1[::-1]
print("Original array: ", arr1)
print("Reversed array: ", reversed)

Original array:  [1 2 0 0 4 0]
Reversed array:  [0 4 0 0 2 1]


In [ ]:
arr = np.ones((5, 5))

arr[1:-1, 1:-1] = 0

print(arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np


checkerboard = np.zeros((8, 8))

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**Problem - 3: Array Operations:**

In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(np.add(x, y))
print()
print(np.add(v, w))


[[ 6  8]
 [10 13]]

[20 22]


In [ ]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(np.subtract(x, y))
print()
print(np.subtract(v, w))

[[-4 -4]
 [-4 -3]]

[-2 -2]


In [ ]:
print("Square of x: ", np.square(x))
print()
print("Square of y: ", np.square(y))
print()

print("Square of v: ", np.square(v))
print()
print("Square of w: ", np.square(w))


Square of x:  [[ 1  4]
 [ 9 25]]

Square of y:  [[25 36]
 [49 64]]

Square of v:  [ 81 100]

Square of w:  [121 144]


In [ ]:
print("Dot product between v and w: ", np.dot(v,w))
print()

print("Dot product between x and y: ", np.dot(x,y))
print()

print("Dot product between x and v: ", np.dot(x,v))
print()

Dot product between v and w:  219

Dot product between x and y:  [[19 22]
 [50 58]]

Dot product between x and v:  [29 77]



In [ ]:
# Using concatenate
concat_rows = np.concatenate([x, y], axis=0)
print("x and y concatenated along rows:\n", concat_rows)

# Using vstack
concat_rows_vstack = np.vstack([x, y])
print("\nx and y using vstack:\n", concat_rows_vstack)

x and y concatenated along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

x and y using vstack:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [ ]:
print(np.concatenate([x, v], axis=0))

# all the arrays must have the same number of dimentsions. since x is 2D and v 1D. they cannot be concatenated.

NameError: name 'np' is not defined

**Problem - 4: Matrix Operations:**


In [ ]:
A = np.array([[3, 4],
              [7, 8]])
B = np.array([[5, 3],
              [2, 1]])


A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A · A⁻¹:", I)

A · A⁻¹: [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("A·B: ", AB)
print()
print("B·A: ", BA)
print()
print("Are they equal?", np.array_equal(AB, BA))


A·B:  [[23 13]
 [51 29]]

B·A:  [[36 44]
 [13 16]]

Are they equal? False


In [ ]:
AB_T = np.dot(A, B).T
B_TA_T = np.dot(B.T, A.T)

print("(AB)ᵀ =\n", AB_T)
print()
print("Bᵀ·Aᵀ =\n", B_TA_T)
print("Are they equal?", np.array_equal(AB_T, B_TA_T))


(AB)ᵀ =
 [[23 51]
 [13 29]]

Bᵀ·Aᵀ =
 [[23 51]
 [13 29]]
Are they equal? True


In [ ]:
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

B_eq = np.array([-1, -3, 9])

X = np.dot(np.linalg.inv(A_eq), B_eq)
print("Solution [x, y, z]: ", X)



Solution [x, y, z]:  [ 2.  1. -2.]


In [ ]:
X_solve = np.linalg.solve(A_eq, B_eq)
print("Solution using np.linalg.solve:", X_solve)


Solution using np.linalg.solve: [ 2.  1. -2.]


**Experiment: How Fast is Numpy?**

In [10]:
import numpy as np
import time


# 1. Element-wise Addition

size = 1_000_000

# Python Lists
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
list_add = [list1[i] + list2[i] for i in range(size)]  # element-wise addition
end = time.time()
print("Python list addition time:", end - start, "seconds")

# NumPy Arrays
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
np_add = arr1 + arr2  # vectorized addition
end = time.time()
print("NumPy array addition time:", end - start, "seconds")


# 2. Element-wise Multiplication


# Python Lists
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(size)]  # element-wise multiplication
end = time.time()
print("Python list multiplication time:", end - start, "seconds")

# NumPy Arrays
start = time.time()
np_mul = arr1 * arr2  # vectorized multiplication
end = time.time()
print("NumPy array multiplication time:", end - start, "seconds")

# 3. Dot Product

# Python Lists
start = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(size))  # compute dot product
end = time.time()
print("Python list dot product time:", end - start, "seconds")

# NumPy Arrays
start = time.time()
dot_np = np.dot(arr1, arr2)  # fast dot product
end = time.time()
print("NumPy array dot product time:", end - start, "seconds")


# 4. Matrix Multiplication (1000x1000)

matrix_size = 100

# Python Lists (nested loops)
matrix1 = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]  # create matrix1
matrix2 = [[i - j for j in range(matrix_size)] for i in range(matrix_size)]  # create matrix2

start = time.time()
# naive Python matrix multiplication (slow)
result_matrix = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(matrix_size))
                  for j in range(matrix_size)]
                 for i in range(matrix_size)]
end = time.time()
print("Python list matrix multiplication time:", end - start, "seconds")

# NumPy Arrays
np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)

start = time.time()
np_result_matrix = np.dot(np_matrix1, np_matrix2)  # fast NumPy matrix multiplication
end = time.time()
print("NumPy matrix multiplication time:", end - start, "seconds")


Python list addition time: 0.11468982696533203 seconds
NumPy array addition time: 0.0027647018432617188 seconds
Python list multiplication time: 0.12735509872436523 seconds
NumPy array multiplication time: 0.0023756027221679688 seconds
Python list dot product time: 0.11213898658752441 seconds
NumPy array dot product time: 0.0019385814666748047 seconds
Python list matrix multiplication time: 0.11571073532104492 seconds
NumPy matrix multiplication time: 0.0010962486267089844 seconds
